### ISSUE TITLE
Return HTTP 404 (or 403?) for unsupported HTTP endpoints

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#237] opened 2022-06-13 22:13 UTC
Based on the role taken on by Janus for a given task, not all HTTP endpoints make sense. We currently return an HTTP 400 in this case (along with all other problem-document errors); we should likely instead return a 404 (or 403?).

**Comment by tgeoghegan** [comment] 2023-10-30 19:02
Dupe of #96

**Closed by tgeoghegan** 2023-10-30 19:02 UTC
