### ISSUE TITLE
Revisit acquire_incomplete_time_interval_collection_jobs() query

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1283] opened 2023-04-24 17:43 UTC
Looking at Query Insights after last week's load tests, the collect job acquisition query took an inordinate amount of time to run on the leader. (See #519 previously) Though it ran only ~500 times during the Prio3Histogram load test with 10 reports per second, it nevertheless was #4 on the list of top queries by database load. The database load and latency both rose over time, and the charts suggest they may scale poorly with larger table sizes.

![image](https://user-images.githubusercontent.com/181772/234072399-b9d41da5-bb4f-4325-9b70-9f33c68e630c.png)

The query was long enough that it got truncated inside Query Insights, but I re-ran it manually to get a query plan.

```
postgres=> EXPLAIN ANALYZE WITH updated AS (UPDATE collection_jobs SET lease_expiry = '2023-04-24 00:00:00', lease_token = gen_random_bytes(16), lease_attempts = lease_attempts + 1 FROM tasks WHERE collection_jobs.id IN (SELECT collection_jobs.id FROM collection_jobs INNER JOIN aggregation_jobs ON collection_jobs.aggregation_param = aggregation_jobs.aggregation_param AND collection_jobs.task_id = aggregation_jobs.task_id AND collection_jobs.batch_interval && aggregation_jobs.client_timestamp_interval WHERE tasks.id = collection_jobs.task_id AND tasks.query_type ? 'TimeInterval' AND collection_jobs.lease_expiry <= '2023-04-24 00:00:00' GROUP BY collection_jobs.id HAVING bool_and(aggregation_jobs.state != 'IN_PROGRESS') LIMIT 10) RETURNING tasks.task_id, tasks.query_type, tasks.vdaf, collection_jobs.collection_job_id, collection_jobs.id, collection_jobs.lease_token, collection_jobs.lease_attempts) SELECT task_id, query_type, vdaf, collection_job_id, lease_token, lease_attempts FROM updated ORDER BY id DESC;

                                                                                                         QUERY PLAN                                                                                                          
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=470774493.09..470775221.09 rows=291200 width=176) (actual time=3000.681..3000.690 rows=20 loops=1)
   Sort Key: updated.id DESC
   Sort Method: quicksort  Memory: 30kB
   CTE updated
     ->  Update on collection_jobs collection_jobs_1  (cost=0.00..470717355.29 rows=291200 width=156) (actual time=7.242..3000.524 rows=20 loops=1)
           ->  Nested Loop  (cost=0.00..470717355.29 rows=291200 width=156) (actual time=1.001..2991.160 rows=20 loops=1)
                 Join Filter: (SubPlan 1)
                 Rows Removed by Join Filter: 3734
                 ->  Seq Scan on collection_jobs collection_jobs_1  (cost=0.00..74.20 rows=1820 width=22) (actual time=0.013..1.619 rows=1877 loops=1)
                 ->  Materialize  (cost=0.00..14.80 rows=320 width=110) (actual time=0.000..0.001 rows=2 loops=1877)
                       ->  Seq Scan on tasks  (cost=0.00..13.20 rows=320 width=110) (actual time=0.005..0.010 rows=2 loops=1)
                 SubPlan 1
                   ->  Limit  (cost=0.69..1615.73 rows=10 width=8) (actual time=0.327..0.793 rows=10 loops=3754)
                         ->  GroupAggregate  (cost=0.69..73485.19 rows=455 width=8) (actual time=0.326..0.792 rows=10 loops=3754)
                               Group Key: collection_jobs.id
                               Filter: bool_and((aggregation_jobs.state <> 'IN_PROGRESS'::aggregation_job_state))
                               ->  Result  (cost=0.69..71187.74 rows=305114 width=12) (actual time=0.292..0.744 rows=371 loops=3754)
                                     One-Time Filter: (tasks.query_type ? 'TimeInterval'::text)
                                     ->  Nested Loop  (cost=0.69..71187.74 rows=305114 width=12) (actual time=0.291..0.706 rows=371 loops=3754)
                                           ->  Index Scan using collection_jobs_pkey on collection_jobs  (cost=0.28..130.36 rows=910 width=39) (actual time=0.269..0.275 rows=11 loops=3754)
                                                 Filter: ((lease_expiry <= '2023-04-24 00:00:00'::timestamp without time zone) AND (task_id = tasks.id))
                                                 Rows Removed by Filter: 817
                                           ->  Index Scan using aggregation_jobs_task_and_client_timestamp_interval on aggregation_jobs  (cost=0.41..71.38 rows=671 width=35) (actual time=0.020..0.034 rows=34 loops=41204)
                                                 Index Cond: ((task_id = tasks.id) AND (client_timestamp_interval && collection_jobs.batch_interval))
                                                 Filter: (collection_jobs.aggregation_param = aggregation_param)
   ->  CTE Scan on updated  (cost=0.00..5824.00 rows=291200 width=176) (actual time=7.249..3000.595 rows=20 loops=1)
 Planning Time: 0.421 ms
 Execution Time: 3000.901 ms
(28 rows)
```

**Comment by branlwyd** [comment] 2023-04-25 16:41
Yeah, this is not great: `->  Seq Scan on collection_jobs collection_jobs_1  (cost=0.00..74.20 rows=1820 width=22) (actual time=0.013..1.619 rows=1877 loops=1)`

IIUC the current query plan correctly, it is sequentially scanning all of the `collection_jobs` rows each time it runs this query, then checking the further requirements of the collection job & related aggregation jobs from there for each candidate collection job. The cost of this query will grow linearly with the number of collection jobs in the system.

I think we should switch to a model where each collection job has a state which indicates when it is ready to be collected, and this query should be redesigned to look to the `state` field (augmented with an index) to find collection jobs which are ready to be handled. However, definining & implementing the state transitions will be nontrivial, since transitioning to this state requires reliably/efficiently detecting when all reports for a given batch have been aggregated (successfully or not).

**Comment by branlwyd** [comment] 2023-04-25 17:25
Oh -- I should evaluate fixing up `acquire_incomplete_fixed_size_collection_jobs` while I'm at it. It uses a very similar query shape & is very likely also unperformant.

**Comment by branlwyd** [comment] 2023-04-26 23:44
There is a race condition between aggregation & collection that can occur if an aggregation job pertaining to a batch is stepped concurrently with a collection job for that batch:

* The Leader creates a collection job is created & picked up to be worked on for a some batch.
* Leader creates an aggregation job for this batch, then runs it to the point it sends the final continuation request to the Helper. The Helper does its thing, including committing aggregates to its batch_aggregates table, and begins sending its response.
* The Leader begins processing of the collection job, changing its own batch_aggregates to be COLLECTED.
* The Leader receives the aggregation response from the Helper, and processes it; it can't commit batches to batch_aggregates because collection has started.

The desired solution is to not allow an aggregation job pertaining to a given batch to run at the same time as a collection job for a given batch; this is inherently racy due to the state updates of the Leader & Helper being (rightfully/mandatorily) non-transactional.

I should evaluate fixing this race condition as part of the update to the collection job lifecycle implied by this issue.

**Comment by branlwyd** [comment] 2023-04-28 21:01
OK, I think I've worked out a design. It's somewhat complicated, so I'm going to write it down before implementing.


### Design summary

The goal of this design is twofold:
* Address the performance issue which currently exists in the collection-job acquiry process, specifically the SQL query in `acquire_incomplete_{time_interval,fixed_size}_collection_jobs`.
* Address the race condition which exists between the aggregation process & the collection process; specifically, do not allow aggregation job processing affecting a given batch to occur concurrently with collection job processing affecting a given batch.

To summarize the design: we introduce additional state explicitly tracking the overall state of aggregation jobs affecting a given batch, applying to tasks for which Janus is in the Leader position for. This state counts the number of created & completed aggregation jobs, as well as a state enumeration allowing the aggregation process & collection process to signal one another. The aggregation creation, aggregation completion, and collection processes are updated to respect this new state.


### `aggregation_state` table

A new `aggregation_state` table will be introduced, whose purpose is to track the overall state of aggregations for a given batch for all tasks for which Janus is in the Leader role for. The primary key will be an artificial ID as with all other tables; the effective primary key will be `(task_id, batch_id, aggregation_param)`. Additionally, this table will track:

* A state, which can be `OPEN`, `CLOSING`, or `CLOSED`. `OPEN` means this batch can accept additional aggregation jobs, `CLOSING` means this batch can accept additional aggregation jobs but will transition to `CLOSED` once there are no outstanding aggregation jobs, and `CLOSED` means this batch can no longer accept additional aggregation jobs and there are no aggregation jobs outstanding.
* A count of created aggregation jobs.
* A count of completed aggregation jobs.

(These rows will be updated at time of aggregation job creation and completion; this may create a practical performance concern due to DB write contention, just as updating the unsharded `batch_aggregations` at time of successful aggregation job completion. If so, the solution will be the same: introduce sharding to the `aggregation_state` table by extending the effective primary key with an `ord` field. In this case, all shards for a given batch should have the same state, and the counts will be sharded.)

Note: another design option would be to add these new fields to the existing `batch_aggregations` table, rather than creating a new table. This information naturally fits into `batch_aggregations` in terms of which parts of the system read/write this data, but the `batch_aggregations` name does not fit so well. However, I don't think we want to rename a pre-existing table if we don't need to.


### Updates to collection job state tracking & lifecycle

Currently, collection jobs have states `START` and `FINISHED` (and a few special terminal states, `ABANDONED` and `DELETED`, which will not change with this design). Collection jobs are created in state `START`; they are picked up by the collection job driver via a SQL query that checks (most importantly) that all associated aggregation jobs are not `IN_PROGRESS`; and the collection job driver then transitions the collection job to state `FINISHED` once processing with the helper is complete.

Now, collection jobs will have states `START`, `COLLECTABLE`, and `FINISHED`. Aggregation jobs will be created in state `START`, will transition to state `COLLECTABLE` once all associated aggregation jobs are complete & it is safe for the collection job driver to process this collection job, and to state `FINISHED` once processing with the helper is complete.

The details of these state transitions will be described in the following sections.


### Updates to aggregation job creation

The aggregation job  creation process will be updated to update the `aggregation_state` table transactionally with creation of a new aggregation job. For each batch affected by a report in the aggregation job:

* If the `aggregation_state` is in state `CLOSED`, `report_aggregations` are created in a `Failed` state with a `BatchCollected` error. (we could also drop these report aggregations entirely, but specifying an explicit error: makes it clearer what the issue was; avoids creating aggregation jobs that may appear not to fit the minimum configured aggregation job size; and will help communicate what the issue is once DAP sends errors from the Leader to the Helper)
* Otherwise, the count of created aggregation jobs is incremented.

Implementation notes: an aggregation job will commonly contain reports from many batches, so the process described above will apply to multiple `aggregation_state` rows for each aggregation job that is written. While `aggregation_state` will (almost surely) be sharded, we might still find it wise to create fewer (perhaps only one) aggregation job per transaction to avoid "false sharing" of write conflicts between aggregation job writes causing unnecessarily-large retries. We will likely use an in-memory change-accumulator, similar to the one used to update batch aggregations, to implement `aggregation_state` updates.


### Updates to aggregation job completion

The aggregation completion process will be updated to update the `aggregation_state table` transactionally with the completion of an aggregation job. Note that both successful & unsuccessful completion (aka abandonment) will trigger this behavior.

On completion, the number of completed aggregation jobs is incremented for each relevant `aggregation_state` row. If this leads to there being no outstanding jobs for some `aggregation_state` row, and the current state is `CLOSING`:
* The aggregation state is updated to `CLOSED`.
* Collection jobs which interest with this batch ID are found; any for which all relevant `aggregation_state`s are `CLOSED` have their state updated to `COLLECTABLE`.


### Updates to collection job creation process

The collection job creation process will be updated to begin the process of closing aggregations for the relevant batches. Specifically, in addition to writing the new collection job, in the same transaction all relevant aggregation states will be updated from `OPEN` to either `CLOSING` (if there are outstanding aggregations remaining) or `CLOSED` (if there are no outstanding aggregations remaining).

Implementation note: to ensure the necessary write conflicts in the face of concurrent operation, as with the batch-aggregation write process, we will need to write rows for any expected-but-missing rows.


### Updates to collection job processing

The collection job acquiry process will change so that its acquiry query will look for unleased collection jobs for tasks that Janus is in the Leader role for in state `COLLECTABLE`. (It will be shaped almost exactly like the similar acquiry query for aggregation jobs.)


### Problems not addressed & other considerations

This change is not phrased in a way that would be easy to make it easy to implement in a backwards-compatible fashion (i.e. as a migration on an existing deployed system). As with other changes, we currently accept this, though this would make things challenging for a hypothetical organization which has already deployed Janus in production.

We don't wait for all reports to be associated with an aggregation job, so creating a collection job (and setting the aggregation state to `CLOSING`) might cause some reports to never be aggregated. This problem exists today and will not be addressed by this work; this work could potentially be extended to address this issue by introducing additional checks before moving aggregation state to `CLOSING`. Most likely this will not need to be addressed until a VDAF which has a nontrivial aggregation parameter, such as Poplar1, needs to be supported.

This design does not touch on when we accept reports for upload. We may accept reports that we (could) know will never be aggregatable. Further improvements here are left for the future.

**Comment by branlwyd** [comment] 2023-05-01 02:38
A few thoughts:

The design suggests sharding the `aggregation_state` table for performance reasons. Unfortunately, this won't work: we trigger a collection job state transition on all outstanding aggregation jobs for a (batch, aggregation param) being completed. However, if `aggregation_state` is sharded, it is possible for the last two aggregation jobs to complete concurrently, both write their completion to `aggregation_state` without incurring a write conflict (because they choose different shards to write to), then both read `aggregation_state` as having one remaining outstanding aggregation job; in this case, neither aggregation job will trigger the collection job state transition & the collection job will be permanently stuck. (This can't happen if `aggregation_state` is not sharded, because both writes would go to the same row, triggering a write-conflict & therefore a retry from one of the writers; on retry, this writer would observe the first writer's contribution to `aggregation_state`, observe that there are no more outstanding aggregation jobs, and trigger collection.)

We might initially implement `aggregation_state` unsharded. However, contention on `batch_aggregation` writes at the end of the aggregation process was a throughput-limiter for the overall system; we might find that an unsharded `aggregation_state` is equally throughput-limiting.


> On the topic of application to Poplar1, I think it might make sense to keep track of the open/closing/closed state at the batch level, not per each combination of batch and aggregation parameter.

Poplar1 will definitely want to track outstanding aggregation jobs per-(batch, aggregation param). I think the states are still useful, too: while `OPEN` won't be used since we won't start generating aggregation jobs until a collection job is created, there's no harm in using `CLOSING`/`CLOSED` & the collection job transition on transition to `CLOSED` will still be necessary.

Poplar1 will need some additional support in generating the aggregation jobs on the second collection request at all, however -- as you point out, we'd want to generate jobs for exactly the same set of reports as the first batch.

**Comment by divergentdave** [comment] 2023-05-01 15:22
While changing the `aggregation_state.state` to `CLOSING` signals to the aggregation job creator to stop creating jobs, the only thing that actually could prevent new aggregation jobs from being created after that point is subsequent write conflicts on the tuples of `aggregation_state`, because we can't have any effect on an already-open transaction that's previously seen an `OPEN` state, and we don't know how many such transactions exist. Rather, the writes of zeroed `aggregation_state` shards by the collection job driver and various writes by the aggregation job driver may conflict with the aggregation job creator's writes, so we'll get conflicts and retries that would ultimately prevent aggregation jobs from being inserted into the database concurrent with collection job processing.

This raises a lower-level database question, since we're depending on write conflicts so much: if two transactions UPDATE the same tuple, is that always a write conflict, or could both updates proceed if they touch mutually exclusive columns? Could both updates proceed if they make changes to mutually exclusive columns, and make no-op updates to overlapping columns? (Since most of our UPDATE queries always write every column, the latter question is most relevant)

**Comment by branlwyd** [comment] 2023-05-01 17:32
My concern with Poplar1 (or other VDAFs with nontrivial aggregation params) is less around stopping creation of jobs, and more generating jobs over exactly the same set of reports each time -- we'll need some additional functionality to ensure this. (e.g. we could stop accepting report uploads for a batch that has reached `CLOSED` for any aggregation parameter, or we could have the second collection for a batch generate aggregation jobs by reading which reports are included in the first collection for that batch, ...)

> This raises a lower-level database question, since we're depending on write conflicts so much: if two transactions UPDATE the same tuple, is that always a write conflict, or could both updates proceed if they touch mutually exclusive columns?

Postgres documentation says that, in Repeatable Read isolation level, any conflicting write to the same row (i.e. tuple) will trigger a serialization failure. From https://www.postgresql.org/docs/current/transaction-iso.html#XACT-REPEATABLE-READ:

> UPDATE, DELETE, MERGE, SELECT FOR UPDATE, and SELECT FOR SHARE commands behave the same as SELECT in terms of searching for target rows: they will only find target rows that were committed as of the transaction start time. However, such a target row might have already been updated (or deleted or locked) by another concurrent transaction by the time it is found. In this case, the repeatable read transaction will wait for the first updating transaction to commit or roll back (if it is still in progress). If the first updater rolls back, then its effects are negated and the repeatable read transaction can proceed with updating the originally found row. But if the first updater commits (and actually updated or deleted the row, not just locked it) then the repeatable read transaction will be rolled back with the message
>
> ```
> ERROR:  could not serialize access due to concurrent update
> ```

**Closed** 2023-05-17 21:59 UTC
